services:
  cwp-db:
    image: postgres:17
    container_name: cwp-db
    restart: no
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: cwp-db
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -U postgres -d cwp-db' ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
